package:
    name: mmarchuk_string_utils
    version: "0.3"
  
source:
  path: ../

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja 
    - boost
    - gtest

test:
  commands:
    - test -f ${PREFIX}/lib/libmmarchuk_string_utils.a  # [not win]
    - test -f ${PREFIX}/include/string_utils.h  # [not win]
    - if not exist %PREFIX%\\Library\\lib\\libmmarchuk_string_utils.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\string_utils.h exit 1  # [win]

about:
  home: https://github.com/marchuknikolay/string_utils
  license: MIT
  summary: Simple library with string utility functions